apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ default "Always" .Values.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: 8080

