apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    name: {{ template "fullname" . }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}
  type: LoadBalancer
